### ISSUE TITLE
Plugin update needed for v5.6.0

### ISSUE THREAD

**Issue by craftzdog** [totoa553/inkdrop-furigana#1]
Hi!

Thank you for creating such a cool plugin.
The desktop v5.6.0 is currently in beta, which comes with a new Markdown renderer.
Your plugin has to be updated to support it.
Please check out the following topic for more details:

[forum.inkdrop.app/t/plugin-update-check-needed-for-supporting-v5-6-0/4117](https://forum.inkdrop.app/t/plugin-update-check-needed-for-supporting-v5-6-0/4117)

Please feel free to ask me anything if you need help to update your plugin!

**Comment by totoa553** [comment]
I've supported new version!(https://github.com/totoa553/inkdrop-furigana/commit/065da2dbb002a1f676a6a26d84c87f729214888a)

**Comment by craftzdog** [comment]
Great! Thank you, totoa553 🙌
